config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'home', to: 'home#index'

  resources :funeral_service_orders
  resources :funerals
  resources :funeral_services
  resources :deceaseds
  resources :users

  resources :mourning_cards do
    member do
      get :show_pdf
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/funeral.rb
class Funeral < ApplicationRecord
  belongs_to :deceased
  enum burial_type: { traditional: 0, cremation: 1, green_burial: 2 }

  validates :funeral_date, :burial_type, :deceased_id, :burial_place, :reception_location, presence: true
  validates :burial_place, :reception_location, length: { minimum: 2, maximum: 50 }
  validates :burial_type, inclusion: { in: burial_types.keys }

  def display_name
    "#{deceased.first_name} #{deceased.last_name} (Funeral Date: #{funeral_date})"
  end
end

app/controllers/funerals_controller.rb
class FuneralsController < ApplicationController
  before_action :set_funeral, only: %i[ show edit update destroy ]

  # GET /funerals or /funerals.json
  def index
    @funerals = Funeral.all
  end

  # GET /funerals/1 or /funerals/1.json
  def show
  end

  # GET /funerals/new
  def new
    @funeral = Funeral.new
  end

  # GET /funerals/1/edit
  def edit
  end

  # POST /funerals or /funerals.json
  def create
    @funeral = Funeral.new(funeral_params)

    respond_to do |format|
      if @funeral.save
        format.html { redirect_to funeral_url(@funeral), notice: "Funeral was successfully created." }
        format.json { render :show, status: :created, location: @funeral }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funeral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funerals/1 or /funerals/1.json
  def update
    respond_to do |format|
      if @funeral.update(funeral_params)
        format.html { redirect_to funeral_url(@funeral), notice: "Funeral was successfully updated." }
        format.json { render :show, status: :ok, location: @funeral }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funeral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funerals/1 or /funerals/1.json
  def destroy
    @funeral.destroy

    respond_to do |format|
      format.html { redirect_to funerals_url, notice: "Funeral was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funeral
      @funeral = Funeral.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funeral_params
      params.require(:funeral).permit(:funeral_id, :deceased_id, :burial_place, :burial_type, :reception_location, :funeral_date)
    end
end

app/helpers/funerals_helper.rb
module FuneralsHelper
end

app/views/funerals/_form.html.erb
<%= form_with(model: funeral, local: true, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
  <% if funeral.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(funeral.errors.count, "error") %> prohibited this funeral from being saved:</h2>

      <ul>
        <% funeral.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :deceased_id, "Select Deceased" %>
    <%= form.collection_select(:deceased_id, Deceased.all, :id, :display_name, { prompt: 'Please select a Deceased' }, { class: 'form-control' }) %>
  </div>

  <div class="mb-3">
    <%= form.label :burial_place, class: "form-label" %>
    <%= form.text_field :burial_place, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= form.label :burial_type, class: "form-label" %>
    <%= form.select :burial_type, Funeral.burial_types.keys, include_blank: true, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :reception_location, class: "form-label" %>
    <%= form.text_field :reception_location, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :funeral_date, class: "form-label" %>
    <%= form.date_field :funeral_date, class: "form-control", required: true %>
  </div>

  <div class="mb-4">
    <%= form.submit class: "btn button-primary mt-2" %>
  </div>
<% end %>

app/views/funerals/_funeral.html.erb
<div class="card mb-4" id="<%= dom_id funeral %>">
  <div class="card-body">
    <p class="card-title">Funeral id: <%= funeral.id %></p>

    <p class="card-text">
      <strong>Deceased:</strong>
      <%= funeral.deceased_id %>
    </p>

    <p class="card-text">
      <strong>Burial Place:</strong>
      <%= funeral.burial_place %>
    </p>

    <p class="card-text">
      <strong>Burial Type:</strong>
      <%= funeral.burial_type %>
    </p>

    <p class="card-text">
      <strong>Reception Location:</strong>
      <%= funeral.reception_location %>
    </p>

    <p class="card-text">
      <strong>Funeral Date:</strong>
      <%= funeral.funeral_date %>
    </p>

  </div>
</div>

app/views/funerals/edit.html.erb
<div class="container mt-5">

  <h1 class="display-4 mb-4">Editing Funeral</h1>

  <div class="mb-4">
    <%= render "form", funeral: @funeral %>
  </div>

  <div class="mt-4">
    <%= link_to "Show this funeral", @funeral, class: "btn button-info me-3" %> |
    <%= link_to "Back to funerals", funerals_path, class: "btn button-secondary ml-3" %>
  </div>

</div>

app/views/funerals/index.html.erb
  <div class="container mt-5">
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <h1 class="display-4 mb-4">Funerals</h1>

    <div id="funerals">
      <% @funerals.each do |funeral| %>
        <div class="card mb-3">
          <div class="card-body">
            <%= render funeral %>
            <p class="mt-2">
              <%= link_to "Show this funeral", funeral, class: "btn button-primary" %>
            </p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="mt-4">
      <%= link_to "New funeral", new_funeral_path, class: "btn button-success" %>
    </div>
  </div>

app/views/funerals/new.html.erb
  <div class="container mt-5">

    <h1 class="display-4 mb-4">New Funeral</h1>

    <div class="mb-4">
      <%= render "form", funeral: @funeral, class: "mb-4" %>
    </div>

    <div>
      <%= link_to "Back to funerals", funerals_path, class: "btn button-secondary" %>
    </div>

  </div>

app/views/funerals/show.html.erb
<div class="container mt-5">

  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <div class="mb-4">
    <%= render @funeral %>
  </div>

  <div class="mt-4 d-flex align-items-center">
    <%= link_to "Edit this funeral", edit_funeral_path(@funeral), class: "btn button-warning me-3" %>
    <span class="me-3">|</span>
    <%= link_to "Back to funerals", funerals_path, class: "btn button-secondary me-3" %>
    <%= button_to "Destroy this funeral", @funeral, method: :delete, class: "btn button-danger", data: { confirm: 'Are you sure?' } %>
  </div>

</div>