config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'home', to: 'home#index'

  resources :funeral_service_orders
  resources :funerals
  resources :funeral_services
  resources :deceaseds
  resources :users

  resources :mourning_cards do
    member do
      get :show_pdf
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/mourning_card.rb
class MourningCard < ApplicationRecord
  belongs_to :funeral

  validates :description, presence: true
  validates :description, length: { minimum: 2, maximum: 500 }

end

app/controllers/mourning_cards_controller.rb
class MourningCardsController < ApplicationController
  before_action :set_mourning_card, only: %i[ show edit update destroy ]

  # GET /mourning_cards or /mourning_cards.json
  def index
    @mourning_cards = MourningCard.all
  end

  # GET /mourning_cards/1 or /mourning_cards/1.json
  def show
  end

  # GET /mourning_cards/new
  def new
    @mourning_card = MourningCard.new
  end

  # GET /mourning_cards/1/edit
  def edit
  end

  # POST /mourning_cards or /mourning_cards.json
  def create
    @mourning_card = MourningCard.new(mourning_card_params)

    respond_to do |format|
      if @mourning_card.save
        format.html { redirect_to mourning_card_url(@mourning_card), notice: "Mourning card was successfully created." }
        format.json { render :show, status: :created, location: @mourning_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mourning_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mourning_cards/1 or /mourning_cards/1.json
  def update
    respond_to do |format|
      if @mourning_card.update(mourning_card_params)
        format.html { redirect_to mourning_card_url(@mourning_card), notice: "Mourning card was successfully updated." }
        format.json { render :show, status: :ok, location: @mourning_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mourning_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mourning_cards/1 or /mourning_cards/1.json
  def destroy
    @mourning_card.destroy

    respond_to do |format|
      format.html { redirect_to mourning_cards_url, notice: "Mourning card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def show_pdf
    mourning_card = MourningCard.find(params[:id])
    pdf = MourningCardPdf.new(mourning_card)
    send_data pdf.render, filename: "mourning_card_#{mourning_card.id}.pdf", type: 'application/pdf'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mourning_card
      @mourning_card = MourningCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mourning_card_params
      params.require(:mourning_card).permit(:card_id, :funeral_id, :description)
    end
end

app/helpers/mourning_cards_helper.rb
module MourningCardsHelper
end

app/views/mourning_cards/_form.html.erb
<%= form_with(model: mourning_card, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
  <% if mourning_card.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(mourning_card.errors.count, "error") %> prohibited this mourning card from being saved:</h4>
      <ul>
        <% mourning_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :funeral_id, "Select Funeral" %>
    <%= form.collection_select(:funeral_id, Funeral.all, :id, :funeral_date, { prompt: 'Please select a funeral' }, { class: 'form-control' }) %>
  </div>

  <div class="mb-3">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit class: 'btn button-primary' %>
  </div>
<% end %>

app/views/mourning_cards/_mourning_card.html.erb
<div class="card mb-4" id="<%= dom_id mourning_card %>">
  <div class="card-body">
    <p class="card-title">Card id: <%= mourning_card.id %></p>
    <p class="card-text"><strong>Funeral:</strong> <%= mourning_card.funeral_id %></p>
    <p class="card-text"><strong>Description:</strong> <%= mourning_card.description %></p>
  </div>
</div>

app/views/mourning_cards/edit.html.erb
<div class="container mt-5">

  <h1 class="display-4 mb-4">Editing Mourning Card</h1>

  <div class="mb-4">
    <%= render "form", mourning_card: @mourning_card %>
  </div>

  <div class="mt-4">
    <%= link_to "Show this mourning card", @mourning_card, class: "btn button-info me-3" %> |
    <%= link_to "Back to mourning cards", mourning_cards_path, class: "btn button-secondary ml-3" %>
  </div>

</div>

app/views/mourning_cards/index.html.erb
<div class="container mt-5">

  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <h1 class="display-4 mb-4">Mourning Cards</h1>

  <div id="mourning_cards">
    <% @mourning_cards.each do |mourning_card| %>
      <%= render mourning_card %>
      <p class="mb-3">
        <%= link_to "Show this mourning card", mourning_card, class: "btn button-primary" %>
      </p>
    <% end %>
  </div>

  <div class="mt-4">
    <%= link_to "New mourning card", new_mourning_card_path, class: "btn button-success" %>
  </div>

</div>

app/views/mourning_cards/new.html.erb
<div class="container mt-5">

  <h1 class="display-4 mb-4">New Mourning Card</h1>

  <div class="mb-4">
    <%= render "form", mourning_card: @mourning_card %>
  </div>

  <div class="mt-4">
    <%= link_to "Back to mourning cards", mourning_cards_path, class: "btn button-secondary" %>
  </div>

</div>

app/views/mourning_cards/show.html.erb
<div class="container mt-5">

  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <div class="mb-4">
    <%= render @mourning_card %>
  </div>

  <%= link_to 'Download Mourning Card as PDF', show_pdf_mourning_card_path(@mourning_card), target: "_blank", class: "btn button-secondary" %>

  <div class="mt-4 d-flex align-items-center">
    <%= link_to "Edit this mourning card", edit_mourning_card_path(@mourning_card), class: "btn button-warning me-3" %>
    <span class="me-3">|</span>
    <%= link_to "Back to mourning cards", mourning_cards_path, class: "btn button-secondary me-3" %>
    <%= button_to "Destroy this mourning card", @mourning_card, method: :delete, class: "btn button-danger", data: { confirm: 'Are you sure?' } %>
  </div>

</div>