config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'home', to: 'home#index'

  resources :funeral_service_orders
  resources :funerals
  resources :funeral_services
  resources :deceaseds
  resources :users

  resources :mourning_cards do
    member do
      get :show_pdf
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/deceased.rb
class Deceased < ApplicationRecord
  belongs_to :user

  validates :first_name, :last_name, :date_of_birth, :date_of_death, presence: true
  validates :first_name, :last_name, length: { minimum: 2, maximum: 50 }
  validates :date_of_birth, :date_of_death, comparison: { less_than: proc { Date.today } }
  # TODO validation below not working because of undefined error, probably needs custom validator
  # validates :date_of_birth, comparison: { less_than: proc { date_of_death } }

  def display_name
    "#{first_name} #{last_name} (Date of Birth: #{date_of_birth})"
  end
end

app/controllers/deceaseds_controller.rb
class DeceasedsController < ApplicationController
  before_action :set_deceased, only: %i[ show edit update destroy ]

  # GET /deceaseds or /deceaseds.json
  def index
    @deceaseds = Deceased.all
  end

  # GET /deceaseds/1 or /deceaseds/1.json
  def show
  end

  # GET /deceaseds/new
  def new
    @deceased = Deceased.new
  end

  # GET /deceaseds/1/edit
  def edit
  end

  # POST /deceaseds or /deceaseds.json
  def create
    @deceased = Deceased.new(deceased_params)
    @deceased.user_id = current_user.id

    respond_to do |format|
      if @deceased.save
        format.html { redirect_to deceased_url(@deceased), notice: "Deceased was successfully created." }
        format.json { render :show, status: :created, location: @deceased }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deceased.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deceaseds/1 or /deceaseds/1.json
  def update
    respond_to do |format|
      if @deceased.update(deceased_params)
        format.html { redirect_to deceased_url(@deceased), notice: "Deceased was successfully updated." }
        format.json { render :show, status: :ok, location: @deceased }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deceased.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deceaseds/1 or /deceaseds/1.json
  def destroy
    @deceased.destroy

    respond_to do |format|
      format.html { redirect_to deceaseds_url, notice: "Deceased was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deceased
      @deceased = Deceased.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deceased_params
      params.require(:deceased).permit(:deceased_id, :user_id, :first_name, :last_name, :date_of_birth, :date_of_death)
    end
end

app/helpers/deceaseds_helper.rb
module DeceasedsHelper
end

app/views/deceaseds/_deceased.html.erb
<div class="card mb-4" id="<%= dom_id deceased %>">
  <div class="card-body">
    <p class="card-text">Deceased id: <%= deceased.id %></p>
    <p class="card-text"><strong>Created by user:</strong> <%= deceased.user.email %></p>
    <p class="card-text"><strong>First Name:</strong> <%= deceased.first_name %></p>
    <p class="card-text"><strong>Last Name:</strong> <%= deceased.last_name %></p>
    <p class="card-text"><strong>Date of Birth:</strong> <%= deceased.date_of_birth %></p>
    <p class="card-text"><strong>Date of Death:</strong> <%= deceased.date_of_death %></p>
  </div>
</div>

app/views/deceaseds/_form.html.erb
<%= form_with(model: deceased, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
  <% if deceased.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(deceased.errors.count, "error") %> prohibited this deceased from being saved:</h2>
      <ul>
        <% deceased.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>
  
  <div class="mb-3">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :date_of_death %>
    <%= form.date_field :date_of_death, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit class: 'btn button-primary' %>
  </div>
<% end %>

app/views/deceaseds/edit.html.erb
<div class="container mt-5">

  <h1 class="display-4 mb-4">Editing Deceased</h1>

  <div class="mb-4">
    <%= render "form", deceased: @deceased %>
  </div>

  <div class="mt-4">
    <%= link_to "Show this deceased", @deceased, class: "btn button-info me-3" %> |
    <%= link_to "Back to deceaseds", deceaseds_path, class: "btn button-secondary ml-3" %>
  </div>

</div>

app/views/deceaseds/index.html.erb
<div class="container mt-5">

  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <h1 class="display-4 mb-4">Deceased's</h1>

  <div id="deceaseds">
    <% @deceaseds.each do |deceased| %>
      <%= render deceased %>
      <p class="mb-3">
        <%= link_to "Show this deceased", deceased, class: "btn button-primary" %>
      </p>
    <% end %>
  </div>

  <div class="mt-4">
    <%= link_to "New deceased", new_deceased_path, class: "btn button-success" %>
  </div>

</div>

app/views/deceaseds/new.html.erb
<div class="container mt-5">

  <h1 class="display-4 mb-4">New Deceased</h1>

  <div class="mb-4">
    <%= render "form", deceased: @deceased %>
  </div>

  <div class="mt-4">
    <%= link_to "Back to deceaseds", deceaseds_path, class: "btn button-secondary" %>
  </div>

</div>

app/views/deceaseds/show.html.erb
<div class="container mt-5">

  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <div class="mb-4">
    <%= render @deceased %>
  </div>

  <div class="mt-4 d-flex align-items-center">
    <%= link_to "Edit this deceased", edit_deceased_path(@deceased), class: "btn button-warning me-3" %>
    <span class="me-3">|</span>
    <%= link_to "Back to deceaseds", deceaseds_path, class: "btn button-secondary me-3" %>
    <%= button_to "Destroy this deceased", @deceased, method: :delete, class: "btn button-danger", data: { confirm: 'Are you sure?' } %>
  </div>

</div>