config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'home', to: 'home#index'

  resources :funeral_service_orders
  resources :funerals
  resources :funeral_services
  resources :deceaseds
  resources :users

  resources :mourning_cards do
    member do
      get :show_pdf
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funeral Service Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="<%= home_path %>">
            <img src="<%= asset_path 'funeral_logo.png' %>" alt="Funeral Logo" height="80">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                <li class="nav-item <%= 'nav-active' if current_page?(home_path) %>">
                    <a class="nav-link" href="<%= home_path %>">Home</a>
                </li>

                <% if user_signed_in? %>
                    <li class="nav-item <%= 'nav-active' if current_page?(funerals_path) %>">
                        <a class="nav-link" href="<%= funerals_path %>">Funerals</a>
                    </li>
                    <li class="nav-item <%= 'nav-active' if current_page?(funeral_services_path) %>">
                        <a class="nav-link" href="<%= funeral_services_path %>">Funeral Services</a>
                    </li>
                    <li class="nav-item <%= 'nav-active' if current_page?(funeral_service_orders_path) %>">
                        <a class="nav-link" href="<%= funeral_service_orders_path %>">Funeral Service Orders</a>
                    </li>
                    <li class="nav-item <%= 'nav-active' if current_page?(mourning_cards_path) %>">
                        <a class="nav-link" href="<%= mourning_cards_path %>">Mourning Cards</a>
                    </li>
                    <li class="nav-item <%= 'nav-active' if current_page?(deceaseds_path) %>">
                        <a class="nav-link" href="<%= deceaseds_path %>">Deceased</a>
                    </li>
                <% end %>

                <% if current_user && current_user.user_role == 'admin' %>
                    <li class="nav-item <%= 'nav-active' if current_page?(users_path) %>">
                        <a class="nav-link" href="<%= users_path %>">Users</a>
                    </li>
                <% end %>
                
                <li class="nav-item">
                    <% if user_signed_in? %>
                        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                    <% else %>
                        <%= button_to "Sign in", new_user_session_path, class: "nav-link" %>
                    <% end %>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        <%= yield %>
    </div>
    <div class="footer">
        <p>Copyright © <%= Time.now.year %> Temple of Death</p>
    </div>
  </body>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>